services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    ports:
      - "8888:3000"
    volumes:
      - /app/node_modules
      - ./my-react-app:/app
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
