FROM node:alpine

#WORKDIR /app
#
#COPY ./my-react-app/package.json .
#COPY ./my-react-app/package-lock.json .

#RUN npm install
#
#COPY . .
#
#CMD ["npm", "start"]

COPY . .

WORKDIR /my-react-app

RUN npm install

CMD ["npm", "run", "dev"]


