services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    stdin_open: true
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - ./my-react-app:/app
    depends_on:
      - db
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: {}
