version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    restart: always
    ports:
      - "8888:3000"
    volumes:
      - /app/node_modules
      - ./my-react-app:/app
    depends_on:
      - db
      - api
  api:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: api
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - /app-api/node_modules
      - ./api:/app-api
    depends_on:
      db:
        condition: service_healthy
  db:
    build:
      context: .
      dockerfile: Dockerfile-db
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
