FROM node:alpine

COPY . .

WORKDIR /my-react-app

RUN npm install \
    && npm install react-bootstrap bootstrap \
    && npm install react-router-dom \
    && npm install @trendmicro/react-sidenav

CMD ["npm", "start"]

